
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDErightUMINUSnonassocPOWERDIVIDE LPAREN MINUS NUM PLUS POWER RPAREN TIMESline : expressionexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expressionexpression : expression POWER expressionexpression : MINUS expression %prec UMINUSexpression : LPAREN expression RPARENexpression : NUM'
    
_lr_action_items = {'MINUS':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,],[3,7,3,3,-9,3,3,3,3,3,-7,7,-2,-3,-4,-5,-6,-8,]),'LPAREN':([0,3,4,6,7,8,9,10,],[4,4,4,4,4,4,4,4,]),'NUM':([0,3,4,6,7,8,9,10,],[5,5,5,5,5,5,5,5,]),'$end':([1,2,5,11,13,14,15,16,17,18,],[0,-1,-9,-7,-2,-3,-4,-5,-6,-8,]),'PLUS':([2,5,11,12,13,14,15,16,17,18,],[6,-9,-7,6,-2,-3,-4,-5,-6,-8,]),'TIMES':([2,5,11,12,13,14,15,16,17,18,],[8,-9,-7,8,8,8,-4,-5,-6,-8,]),'DIVIDE':([2,5,11,12,13,14,15,16,17,18,],[9,-9,-7,9,9,9,-4,-5,-6,-8,]),'POWER':([2,5,11,12,13,14,15,16,17,18,],[10,-9,10,10,10,10,10,10,None,-8,]),'RPAREN':([5,11,12,13,14,15,16,17,18,],[-9,-7,18,-2,-3,-4,-5,-6,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'line':([0,],[1,]),'expression':([0,3,4,6,7,8,9,10,],[2,11,12,13,14,15,16,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> line","S'",1,None,None,None),
  ('line -> expression','line',1,'p_line','main.py',92),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','main.py',99),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','main.py',100),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','main.py',101),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','main.py',102),
  ('expression -> expression POWER expression','expression',3,'p_expression_pow','main.py',126),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','main.py',143),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','main.py',157),
  ('expression -> NUM','expression',1,'p_expression_number','main.py',161),
]
